r"""Write the README's data source and add-on tables from the registry.

The README lists every data source the app generates and every Splunk add-on
those sources need. Typed by hand, both tables would go stale the first time a
source was added — the failure this project's registry-wide tests exist to
prevent. So they are rendered from `log-generator/ta_registry.py`, the single
source of truth, between two markers in README.md:

    <!-- BEGIN data-sources (generated by tools/readme_sources.py) -->
    <!-- END data-sources -->

`tests/test_readme_sources.py` renders them again and fails when the README
disagrees, naming the command that fixes it:

    python tools/readme_sources.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "log-generator"))

from catalog import build_catalog  # noqa: E402

README = ROOT / "README.md"
BEGIN = "<!-- BEGIN data-sources (generated by tools/readme_sources.py) -->"
END = "<!-- END data-sources -->"


def render(catalog: dict | None = None) -> str:
    """The two tables, as they belong between the markers.

    Read from the same catalog the app serves, add-on grouping included, so the
    repository README and the in-app Read Me tab list exactly the same thing.
    """
    catalog = catalog or build_catalog()

    lines = [
        "### Data sources",
        "",
        "| Source | Splunk sourcetypes | Add-on |",
        "|---|---|---|",
    ]
    for source in catalog["sources"]:
        sourcetypes = ", ".join(f"`{st['name']}`" for st in source["sourcetypes"])
        lines.append(f"| {source['name']} | {sourcetypes} | {source['add_on']} |")

    lines += [
        "",
        "### Add-ons to install in Splunk",
        "",
        "| Add-on | Package | Checked against | Used by |",
        "|---|---|---|---|",
    ]
    for add_on in catalog["add_ons"]:
        lines.append(f"| [{add_on['name']}]({add_on['url']}) | `{add_on['package']}` "
                     f"| {add_on['version']} | {', '.join(add_on['used_by'])} |")
    return "\n".join(lines)


def splice(readme: str, tables: str) -> str:
    """The README with its generated block replaced, everything else untouched."""
    head, found, rest = readme.partition(BEGIN)
    if not found:
        raise SystemExit(f"README.md has no {BEGIN!r} marker")
    _, found, tail = rest.partition(END)
    if not found:
        raise SystemExit(f"README.md has no {END!r} marker")
    return f"{head}{BEGIN}\n{tables}\n{END}{tail}"


def main() -> None:
    current = README.read_text()
    updated = splice(current, render())
    if updated == current:
        print("README.md is already up to date")
        return
    README.write_text(updated)
    print(f"README.md updated: {len(build_catalog()['sources'])} data sources")


if __name__ == "__main__":
    main()
